name: cetalks
description: A new Flutter project.

publish_to: "none"

version: 5.1.0+15

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audio_service: ^0.18.10
  audio_session: ^0.1.5
  cloud_firestore: ^4.8.0
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.3
  firebase_core: ^2.13.1
  firebase_crashlytics: ^3.3.2
  firebase_messaging: ^14.6.2
  flutter_blurhash: ^0.7.0
  fluttertoast: ^8.0.7
  font_awesome_flutter: ^10.4.0
  google_fonts: ^4.0.4
  google_sign_in: ^6.1.4
  intl: ^0.18.1
  just_audio: ^0.9.34
  polls: ^1.0.1
  provider: ^6.0.5
  shared_preferences: ^2.0.6
  sleek_circular_slider: ^2.0.0
  sliding_up_panel: ^2.0.0+1
  url_launcher: ^6.0.6
  volume_watcher: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/cetalks.png
    - assets/images/load.gif

  fonts:
    - family: BalooChettan2
      fonts:
        - asset: assets/fonts/BalooChettan2-Regular.ttf
